### ISSUE TITLE
`entr_in.b_mean` is not defined anywhere

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/SCAMPy#21]
`entr_in.b_mean` is not defined anywhere in the code.

This variable is used [here](https://github.com/climate-machine/SCAMPy/blob/master/turbulence_functions.pyx#L83) and [here](https://github.com/climate-machine/SCAMPy/blob/master/turbulence_functions.pyx#L98), which means that any case using `entr_detr_buoyancy_sorting` is broken. So, far, I've confirmed broken cases include:

 - TRMM_LBA

Note: I realize that this value may default to zero (which may be correct) depending on compiler/machine configuration, but I think this variable should be explicitly defined.

**Comment by ilopezgp** [comment]
@charleskawczynski you are right. Maybe @yairchn has already solved this issue in this updated branch for entrainment and detrainment, but not on this one.

**Comment by ilopezgp** [comment]
entr_in.b_mean is now defined in Turbulence_PrognosticTKE.pyx
