### ISSUE TITLE
Bug in updraft buoyancy computation when `UpdVar.Area.values[i,k] <= 1e-3`

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/SCAMPy#22]
Just to note, it appears that the definition of `h` [here](https://github.com/climate-machine/SCAMPy/blob/master/EDMF_Updrafts.pyx#L334) should be moved to the line before where it is used [here](https://github.com/climate-machine/SCAMPy/blob/master/EDMF_Updrafts.pyx#L340-L341).

I think the area fraction is clipped, so this shouldn't have any effect. However, if this clipping tolerance does not match the hard-coded `1e-3` here, then this will likely result in issues.

**Comment by ilopezgp** [comment]
Changed buoyancy computation to address this issue.
