### ISSUE TITLE
division by zero error in pressure_tan18_buoy

### ISSUE THREAD

**Issue by trontrytel** [climate-machine/SCAMPy#53]
I'm getting many of those errors: 

```Exception ZeroDivisionError: 'float division' in 'turbulence_functions.pressure_tan18_buoy' ignored```

For now I commented out those lines:
```
namelist['turbulence']['EDMF_PrognosticTKE']['pressure_closure_buoy'] = 'tan18'
namelist['turbulence']['EDMF_PrognosticTKE']['pressure_closure_drag'] = 'tan18'
namelist['turbulence']['EDMF_PrognosticTKE']['pressure_closure_asp_label'] = 'median'
```

@jiahe23  - could you check that?

**Comment by jiahe23** [comment]
In fact, it is the issue of assigning "median" to namelist['turbulence']['EDMF_PrognosticTKE']['pressure_closure_asp_label']

I have resolved in #55
